name: Daily newsletter workflow

on:
  schedule:
    # Send the newsletter daily at 7:15 am.
    # If your not familiar with cron, this can ease the configuration https://crontab.guru/#15_7_*_*_* 
    - cron: '20,25 11 * * *'
  # This allows you to manually run the workflow in the repository's "Actions" tab.
  workflow_dispatch:

jobs:
  Query-And-Notification:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install python-dotenv
      - name: Send the newsletter to the subscribers
        env:
          GMAIL_USERNAME: intospectro.newsletter@gmail.com
          GMAIL_PASSWORD: zldt fevv sxat bnim
        run: |
          python newsletter.py